### ISSUE TITLE
Issue: Multilevel project submissions seem to break

### ISSUE THREAD

**Issue by 4onen** [adsnaider/Git-Scope#2]
![Screenshot](https://user-images.githubusercontent.com/11580688/80128544-ae813980-854a-11ea-8159-cd89ca9b1970.PNG)

The OOPlant repo where this triggered is up at https://github.com/4onen/CSRestruc-OOPlant.
The submission was just a zip file, called `given.zip` containing exactly the result of `make student_pack` in the CSRestruc-OOPlant repo.

**Comment by 4onen** [comment]
Resolving my other build error did not resolve the copy operation issue. See the new screenshot:
![Annotation 2020-04-23 114501](https://user-images.githubusercontent.com/11580688/80137336-f78bba80-8557-11ea-89c4-4bfb5c8418b3.jpg)

**Comment by adsnaider** [comment]
Should be fixed now: See 6dcb23330ffc8fc4347b7892902d3e7692cc6211
